# Docker Compose configuration

services:
  scalping-bot:
    build: .
    container_name: scalping-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    ports:
      - "8080:8080"
